using System;
using System.Collections.Generic;

internal sealed class CompilerSession
{
    public bool EnableDebugOutput;
    public bool DisableDisasm;
    public bool EnableIncrementalCache = true;
    public bool EmitDiagJson;
    public string DiagJsonPath = "kitaqgb.diag.json";
    public bool EmitAiMetadata;
    public string AiMetadataPath = "";
    public bool EmitDependenciesList;
    public string DependenciesListPath = "";
    public Program.DiagnosticMode DiagnosticsMode = Program.DiagnosticMode.Permissive;
    public readonly List<string> IncludeDirectories = new List<string>();
    public readonly List<string> LastCompilationDependencies = new List<string>();
    public string CacheKey = "";
    public string[] OriginalArgs = new string[0];
    public bool AutoMinimizeOnFail;
    public bool AutoMinimizeTriggered;
    public bool ReproPackageWritten;
    public string OutputFilenameForDiag = "out.gb";
    public bool RstUse38;
    public bool RstDisable = true;
    public bool ConstScalarInRom;
    public int RstMaxCalls = int.MaxValue;
    public int RstMaxVectors;
    public readonly HashSet<string> RstExcludeLabels = new HashSet<string>(StringComparer.Ordinal);
    public bool RstSpeedSafe;
    public bool RstUnsafe;
    public bool AttachDebuggerOnError;
    public readonly List<Program.DiagnosticEntry> Diagnostics = new List<Program.DiagnosticEntry>();
    public bool SuppressConsoleDiagnostics;
    public int ErrorCount;
    public int WarningCount;
    public int MaxErrors = 20;
    public readonly Dictionary<string, string[]> SourceCache = new Dictionary<string, string[]>(StringComparer.Ordinal);
    public string DebugOutputPath = "debug_output";
    public bool TraceEnabled;
    public string TraceOutputPath = "trace_output";
    public readonly HashSet<string> TraceStages = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    public bool EmitChangedFunctionDisasm;
    public string ChangedFunctionDisasmBaseRef = "";
    public string ChangedFunctionDisasmOutPath = "";
    public readonly Dictionary<string, int> FunctionBankOverrides = new Dictionary<string, int>(StringComparer.Ordinal);
    public bool EmitVarList;
    public string VarListOutputPath = "";
    public int OptLevel;
    public bool CheckBounds;
    public bool CheckMemCopy;
    public bool CheckStack;
    public bool CheckBankCalls;
    public bool CheckSliceBounds;
    public Program.StackBankMode StackBank = Program.StackBankMode.WramX1;
    public int? StackTop;
    public int StackReserve;
    public bool StackReserveSpecified;
    public int EffectiveStackTop = 0xDFFF;
    public int EffectiveStackAutoLimit = 0xDFFF;
    public Program.AbiMode Abi = Program.AbiMode.Legacy;
    public bool EmitBankSimReport;
    public string BankSimReportPath = "";
    public bool EmitFarcallSuggestionReport;
    public string FarcallSuggestionReportPath = "";
    public bool EmitCrossBankCallReport;
    public string CrossBankCallReportPath = "";
    public bool EmitAbiVerifyReport;
    public string AbiVerifyReportPath = "";
    public bool EmitAbiDiffReport;
    public string AbiDiffReportPath = "";
    public bool EmitRstApplyReport;
    public string RstApplyReportPath = "";
    public bool EmitOptDiffReport;
    public string OptDiffReportPath = "";
    public bool EmitFunctionSizeReport;
    public string FunctionSizeReportPath = "";
    public bool EmitHotspotReport;
    public string HotspotReportPath = "";
    public bool EnableReproCheck;
    public string ReproCheckReportPath = "";
    public bool EmitCgbConsistencyReport;
    public string CgbConsistencyReportPath = "";
    public bool EmitCgbSymbolVerifyReport;
    public string CgbSymbolVerifyReportPath = "";
    public bool EmitReproPackageOnFail;
    public string ReproPackagePath = "";
    public readonly RomHeaderOptions RomHeader = new RomHeaderOptions();
    public readonly RomHeaderOptions RomHeaderPragma = new RomHeaderOptions();
    public readonly List<Program.CgbPaletteDefinition> CgbPalettePragmas = new List<Program.CgbPaletteDefinition>();
    public CompilerHostMode HostMode = CompilerHostMode.Cli;
    public readonly Dictionary<string, string> ArtifactPaths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    public bool MachineReadableOutput;
    public bool NoBanner;
    public bool EmitPathManifest;
    public string PathManifestPath = "";
    public CodegenAnalysisReport CodegenLastReport = new CodegenAnalysisReport();
    public AssemblerAnalysisReport AssemblerLastReport = new AssemblerAnalysisReport();
    public OptimizerAnalysisReport OptimizerLastReport = new OptimizerAnalysisReport();
}
