// Native return-type table generated from the verified compiler surface.
use super::*;
pub(super) fn intrinsic_type(name: &str) -> Option<CType> {
    Some(CType::simple(match name {
        "__bankswitch"
        | "__bit_clear"
        | "__bit_set"
        | "__bit_toggle"
        | "__cgb_safe_set_bcpd"
        | "__cgb_safe_set_bcps"
        | "__cgb_safe_set_bgpd"
        | "__cgb_safe_set_bgpi"
        | "__cgb_safe_set_hdma1"
        | "__cgb_safe_set_hdma2"
        | "__cgb_safe_set_hdma3"
        | "__cgb_safe_set_hdma4"
        | "__cgb_safe_set_hdma5"
        | "__cgb_safe_set_obpd"
        | "__cgb_safe_set_obpi"
        | "__cgb_safe_set_ocpd"
        | "__cgb_safe_set_ocps"
        | "__cgb_safe_set_svbk"
        | "__cgb_safe_set_vbk"
        | "__copy16"
        | "__copy32"
        | "__critical_leave"
        | "__far_memcpy"
        | "__farcall_ptr"
        | "__farmemcpy"
        | "__fill_tilemap"
        | "__memcpy"
        | "__memcpy_small"
        | "__memset"
        | "__memset_small"
        | "__oam_dma"
        | "__padrep_init"
        | "__padrep_reset"
        | "__rng_seed"
        | "__scroll_bg_add"
        | "__scroll_bg_set"
        | "__scroll_bg_set_buffered"
        | "__scroll_bg_x_set"
        | "__scroll_bg_x_set_buffered"
        | "__scroll_bg_y_set"
        | "__scroll_bg_y_set_buffered"
        | "__scroll_flush"
        | "__scroll_split_commit"
        | "__scroll_split_push"
        | "__scroll_split_push_ex"
        | "__scroll_split_reset"
        | "__scroll_win_add"
        | "__scroll_win_hide"
        | "__scroll_win_set"
        | "__scroll_win_set_buffered"
        | "__scroll_win_show"
        | "__scroll_win_x_set"
        | "__scroll_win_x_set_buffered"
        | "__scroll_win_y_set"
        | "__scroll_win_y_set_buffered"
        | "__settile"
        | "__settile_bulk"
        | "__settile_bulk_fast"
        | "__settile_col"
        | "__settile_fast"
        | "__settile_rect"
        | "__settile_row"
        | "__settile_unsafe"
        | "__settile_xy"
        | "__settileat"
        | "__settileat_unsafe"
        | "__settileatattr"
        | "__settileatattr_unsafe"
        | "__settileatcgb"
        | "__settileatcgb_unsafe"
        | "__settileattr"
        | "__settileattr_bulk"
        | "__settileattr_bulk_fast"
        | "__settileattr_unsafe"
        | "__settilebg"
        | "__settilebg16_buf"
        | "__settilebg16_flush"
        | "__settilebg16cgb_buf"
        | "__settilebg16cgb_flush"
        | "__settilebg_unsafe"
        | "__settilebgattr"
        | "__settilebgattr_unsafe"
        | "__settilebgcgb"
        | "__settilebgcgb_unsafe"
        | "__settilecgb"
        | "__settilecgb_bulk"
        | "__settilecgb_bulk_fast"
        | "__settilecgb_unsafe"
        | "__settilemap_rect"
        | "__settilewin"
        | "__settilewin_unsafe"
        | "__settilewinattr"
        | "__settilewinattr_unsafe"
        | "__settilewincgb"
        | "__settilewincgb_unsafe"
        | "__sram_write8"
        | "__vram_copy"
        | "__vram_copy_dma"
        | "__vram_copy_hblank"
        | "__vram_fill"
        | "__vram_memcpy"
        | "__vram_memcpy_unsafe"
        | "__vram_memset"
        | "__vram_memset_unsafe"
        | "__wait_ly"
        | "__wait_vblank"
        | "gbfb_begin_frame"
        | "gbfb_clear"
        | "gbfb_init"
        | "gbfb_line"
        | "gbfb_plot"
        | "gbfb_present"
        | "gbfb_triangle" => Simple::Void,
        "__bankof" | "__bit_test" | "__cgb_is_cgb" | "__critical_enter" | "__farpeek8"
        | "__manhattan" | "__mul8x8_hi" | "__padrep" | "__padrep_down" | "__padrep_lr"
        | "__padrep_mask" | "__readpad" | "__readpadbtn" | "__readpaddir" | "__rng8"
        | "__scroll_bg_x_get" | "__scroll_bg_y_get" | "__scroll_win_x_get"
        | "__scroll_win_y_get" | "__sram_read8" | "__svbk_get" | "__svbk_set" | "__xy_in_rect" => {
            Simple::UInt8
        }
        "__dot2_q8_8" | "__dot3_q8_8" | "__farpeek16" | "__getbgmapbase" | "__getwinmapbase"
        | "__mac16" | "__map_index" | "__mul16x8" | "__readpadex" | "__rle_decode_vram"
        | "__sdot2_q1_7" | "__sdot2_q8_8" | "__sdot3_q1_7" | "__sdot3_q8_8" | "__smac16"
        | "__smac16_q1_7" | "__smul16x8" | "__smul16x8_q1_7" | "__tile_addr" => Simple::UInt16,
        _ => return None,
    }))
}
