//! Token kinds preserve the original diagnostic names and numeric order.
use crate::expr::Position;
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Kind {
    INVALID,
    EOF,
    NEWLINE,
    LOGICAL_NOT,
    NOT_EQUAL,
    NUMBER_SIGN,
    PERCENT,
    AMPERSAND,
    LPAREN,
    RPAREN,
    STAR,
    PLUS,
    COMMA,
    MINUS,
    ARROW,
    PERIOD,
    SLASH,
    COLON,
    SEMICOLON,
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    EQUAL,
    DOUBLE_EQUAL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    QUESTION_MARK,
    LBRACKET,
    RBRACKET,
    CARET,
    LBRACE,
    PIPE,
    RBRACE,
    TILDE,
    INCREMENT,
    DECREMENT,
    SHIFT_LEFT,
    SHIFT_RIGHT,
    LOGICAL_OR,
    LOGICAL_AND,
    PLUS_EQUALS,
    MINUS_EQUALS,
    STAR_EQUALS,
    SLASH_EQUALS,
    PERCENT_EQUALS,
    SHIFT_LEFT_EQUALS,
    SHIFT_RIGHT_EQUALS,
    AMPERSAND_EQUALS,
    PIPE_EQUALS,
    CARET_EQUALS,
    INT,
    NAME,
    STRING,
    PRAGMA_BANK,
    PRAGMA_FIXED_BANK,
    PRAGMA_FIXED_ORDER,
    PRAGMA_REGION,
    PRAGMA_WRAMX_BANK,
    PRAGMA_ALIGN,
    PRAGMA_SECTION,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: Kind,
    pub integer: i32,
    pub name: Option<String>,
    pub position: Position,
}
impl Token {
    pub fn new(kind: Kind, position: Position) -> Self {
        Self {
            kind,
            integer: 0,
            name: None,
            position,
        }
    }
    pub fn show(&self) -> String {
        match self.kind {
            Kind::INT => self.integer.to_string(),
            Kind::NAME => self.name.clone().unwrap_or_default(),
            Kind::STRING => format!("\"{}\"", self.name.as_deref().unwrap_or_default()),
            _ => format!("{:?}", self.kind),
        }
    }
}
impl Kind {
    pub fn spelling(self) -> &'static str {
        const NAMES: [&str; 59] = [
            "(invalid)",
            "EOF",
            "newline",
            "!",
            "!=",
            "#",
            "%",
            "&",
            "(",
            ")",
            "*",
            "+",
            ",",
            "-",
            "->",
            ".",
            "/",
            ":",
            ";",
            "<",
            "<=",
            "=",
            "==",
            ">",
            ">=",
            "?",
            "[",
            "]",
            "^",
            "{",
            "|",
            "}",
            "~",
            "++",
            "--",
            "<<",
            ">>",
            "||",
            "&&",
            "+=",
            "-=",
            "*=",
            "/=",
            "%=",
            "<<=",
            ">>=",
            "&=",
            "|=",
            "^=",
            "(int)",
            "(name)",
            "(string)",
            "(pragma_bank)",
            "(pragma_fixed_bank)",
            "(pragma_fixed_order)",
            "(pragma_region)",
            "(pragma_wramx_bank)",
            "(pragma_align)",
            "(pragma_section)",
        ];
        NAMES[self as usize]
    }
}
